export const DEX_ABI = [
  { type: "constructor", inputs: [{ name: "tokenAddr", type: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "deposit", inputs: [], outputs: [{ name: "tokensDeposited", type: "uint256" }], stateMutability: "payable" },
  { type: "function", name: "deposit", inputs: [{ name: "maxTokenAmount", type: "uint256" }, { name: "deadline", type: "uint256" }], outputs: [{ name: "tokensDeposited", type: "uint256" }], stateMutability: "payable" },
  { type: "function", name: "ethToToken", inputs: [], outputs: [{ name: "tokenOutput", type: "uint256" }], stateMutability: "payable" },
  { type: "function", name: "ethToToken", inputs: [{ name: "minTokenOutput", type: "uint256" }, { name: "deadline", type: "uint256" }], outputs: [{ name: "tokenOutput", type: "uint256" }], stateMutability: "payable" },
  { type: "function", name: "getLiquidity", inputs: [{ name: "lp", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getSpotPrice", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "init", inputs: [{ name: "tokens", type: "uint256" }], outputs: [{ name: "initialLiquidity", type: "uint256" }], stateMutability: "payable" },
  { type: "function", name: "liquidity", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "price", inputs: [{ name: "xInput", type: "uint256" }, { name: "xReserves", type: "uint256" }, { name: "yReserves", type: "uint256" }], outputs: [{ name: "yOutput", type: "uint256" }], stateMutability: "pure" },
  { type: "function", name: "token", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "tokenToEth", inputs: [{ name: "tokenInput", type: "uint256" }, { name: "minEthOutput", type: "uint256" }, { name: "deadline", type: "uint256" }], outputs: [{ name: "ethOutput", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "tokenToEth", inputs: [{ name: "tokenInput", type: "uint256" }], outputs: [{ name: "ethOutput", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "totalLiquidity", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "withdraw", inputs: [{ name: "amount", type: "uint256" }], outputs: [{ name: "ethAmount", type: "uint256" }, { name: "tokenAmount", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "withdraw", inputs: [{ name: "amount", type: "uint256" }, { name: "minEthAmount", type: "uint256" }, { name: "minTokenAmount", type: "uint256" }, { name: "deadline", type: "uint256" }], outputs: [{ name: "ethAmount", type: "uint256" }, { name: "tokenAmount", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "event", name: "EthToTokenSwap", inputs: [{ name: "swapper", type: "address", indexed: true }, { name: "tokenOutput", type: "uint256", indexed: false }, { name: "ethInput", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "LiquidityProvided", inputs: [{ name: "liquidityProvider", type: "address", indexed: true }, { name: "liquidityMinted", type: "uint256", indexed: false }, { name: "ethInput", type: "uint256", indexed: false }, { name: "tokensInput", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "LiquidityRemoved", inputs: [{ name: "liquidityRemover", type: "address", indexed: true }, { name: "liquidityWithdrawn", type: "uint256", indexed: false }, { name: "tokensOutput", type: "uint256", indexed: false }, { name: "ethOutput", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "TokenToEthSwap", inputs: [{ name: "swapper", type: "address", indexed: true }, { name: "tokensInput", type: "uint256", indexed: false }, { name: "ethOutput", type: "uint256", indexed: false }], anonymous: false },
  { type: "error", name: "DeadlineExpired", inputs: [{ name: "deadline", type: "uint256" }, { name: "blockTimestamp", type: "uint256" }] },
  { type: "error", name: "DexAlreadyInitialized", inputs: [] },
  { type: "error", name: "EthTransferFailed", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }] },
  { type: "error", name: "InsufficientLiquidity", inputs: [{ name: "available", type: "uint256" }, { name: "required", type: "uint256" }] },
  { type: "error", name: "InvalidEthAmount", inputs: [] },
  { type: "error", name: "InvalidTokenAmount", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "SlippageExceeded", inputs: [{ name: "received", type: "uint256" }, { name: "minimum", type: "uint256" }] },
  { type: "error", name: "TokenDepositExceedsMax", inputs: [{ name: "required", type: "uint256" }, { name: "maximum", type: "uint256" }] },
  { type: "error", name: "TokenTransferFailed", inputs: [] },
  { type: "error", name: "ZeroReserves", inputs: [] },
] as const;

export const ERC20_ABI = [
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "allowance", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
] as const;
